table dim_vehiculo
	lineageTag: 2f07ee16-0f27-4271-8f3f-aa51278b1b1f

	column id_vehiculo
		dataType: int64
		formatString: 0
		lineageTag: 8aac8ed2-c89d-433e-b23a-2e7dcf1a7e40
		summarizeBy: none
		sourceColumn: id_vehiculo

		annotation SummarizationSetBy = Automatic

	column marca_vehiculo
		dataType: string
		lineageTag: 087fe893-6140-4ad8-a3aa-1883bfe8299e
		summarizeBy: none
		sourceColumn: marca_vehiculo

		annotation SummarizationSetBy = Automatic

	column modelo_vehiculo
		dataType: string
		lineageTag: c91992ca-c06c-41a8-a002-5475a33ab8d8
		summarizeBy: none
		sourceColumn: modelo_vehiculo

		annotation SummarizationSetBy = Automatic

	column tipo_vehiculo
		dataType: string
		lineageTag: 938f44af-5111-4dd5-95fd-876a1b60685f
		summarizeBy: none
		sourceColumn: tipo_vehiculo

		annotation SummarizationSetBy = Automatic

	column año_vehiculo
		dataType: int64
		formatString: 0
		lineageTag: 7d5264a2-14ba-4725-ad37-000f69916096
		summarizeBy: none
		sourceColumn: año_vehiculo

		annotation SummarizationSetBy = Automatic

	partition dim_vehiculo = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\dmeji\Downloads\VentasVehiculos.xlsx"), null, true),
				    dim_vehiculo_Table = Origen{[Item="dim_vehiculo",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(dim_vehiculo_Table,{{"id_vehiculo", Int64.Type}, {"marca_vehiculo", type text}, {"modelo_vehiculo", type text}, {"tipo_vehiculo", type text}, {"año_vehiculo", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

